### ISSUE TITLE
Not an issue just a thank you!

### ISSUE THREAD

**Issue by houser42** [password123456/setup-selenium-with-chrome-driver-on-ubuntu_debian#1]
Not an issue just a thank you!
Maintaining the combo of chrome and chrome driver on Ubuntu has issues and goes out of synch and becomes non functional now and then and needs synching of versions again to work properly.
I will try to use this to fix that. Has now worked once ;) Thanks again!

**Comment by password123456** [comment]
I'm glad this post was helpful. 
I'll continue to share other useful tips, guides, and miscellaneous but handy tools in the future
