### ISSUE TITLE
urllib3 ({}) or chardet ({}) doesn't match a supported

### ISSUE THREAD

**Issue by zxczxcdev** [password123456/setup-selenium-with-chrome-driver-on-ubuntu_debian#2]
tôi đã làm theo hướng dẫn của bạn với google-chrome --version
Google Chrome 120.0.6099.129
và đây là lỗi tôi gặp phải : 
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.1.0) or chardet (5.2.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
```

**Comment by zxczxcdev** [comment]
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"

**Comment by zxczxcdev** [comment]
i have fixed it ! with pip3 install --upgrade requests

**Comment by password123456** [comment]
Thanks buddy :)
