### ISSUE TITLE
Broken link to chromedriver in debian

### ISSUE THREAD

**Issue by pjm002** [password123456/setup-selenium-with-chrome-driver-on-ubuntu_debian#4]
When using chromedriver in debian 12 there seems to be an error in that the webdriver/common/service.py looks like it is trying
to open a text file ~/.wdm/drivers/chromedriver/linux64/127.0.6533.43/chromedriver linux64/THIRD_PARTY_NOTICES.chromedriver
rather than the executable file chromedriver which is in the same directory.

I can "fix" this by renaming the executable as THIRD_PARTY_NOTICES.chromedriver after moving the original text file out of the
way but this seems to be some form of bug that I am currently unable to fix.

Code is as follows:

def chromeStart(headless: bool):
    """ Start Chrome """
    os.system('killall chrome ; killall chromedriver')
    dc = webdriver.DesiredCapabilities.CHROME
    prof_extentions = {"download.default_directory": '/home/dirname/data/',
                       "download.prompt_for_download": False,
                       "download.directory_upgrade": True,
                       "plugins.always_open_pdf_externally": True}

    chrome_profile = webdriver.ChromeOptions()
    chrome_profile.add_experimental_option('prefs', prof_extentions)
    if headless:
        # https://developer.chrome.com/articles/new-headless/
        # need to add =new to get it to work
        chrome_profile.add_argument("--headless=new")

    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()),options=chrome_profile)
    driver.implicitly_wait(5) # don't know what this does!
    return driver
    
The error that is returned is as follows:
Traceback (most recent call last):
  File "/home/pjm/prj/poa/getdata.py", line 142, in <module>
    browser = chromeStart('--browser' not in sys.argv) 
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pjm/prj/poa/getdata.py", line 34, in chromeStart
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()),options=chrome_profile)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self._start_process(self._path)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/common/service.py", line 208, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pjm/.wdm/drivers/chromedriver/linux64/127.0.6533.43/chromedriver-linux64/THIRD_PARTY_NOTICES.chromedriver'

**Comment by pjm002** [comment]
After debugging the code the error seems to be in ~/.wdm/drivers.json which reflects the wrong executable for 127.0 versions:

    "linux64_chromedriver_126.0.6478.61_for_126.0.6478": {
        "timestamp": "16/06/2024",
        "binary_path": "/home/pjm/.wdm/drivers/chromedriver/linux64/126.0.6478.61/chromedriver-linux64/chromedriver"
    },
    "linux64_chromedriver_127.0.6533.17_for_127.0.6533": {
        "timestamp": "23/06/2024",
        "binary_path": "/home/pjm/.wdm/drivers/chromedriver/linux64/127.0.6533.17/chromedriver-linux64/THIRD_PARTY_NOTICES.chromedriver"
    },
    "linux64_chromedriver_127.0.6533.26_for_127.0.6533": {
        "timestamp": "11/07/2024",
        "binary_path": "/home/pjm/.wdm/drivers/chromedriver/linux64/127.0.6533.26/chromedriver-linux64/THIRD_PARTY_NOTICES.chromedriver"
    },
    "linux64_chromedriver_127.0.6533.43_for_127.0.6533": {
        "timestamp": "12/07/2024",
        "binary_path": "/home/pjm/.wdm/drivers/chromedriver/linux64/127.0.6533.43/chromedriver-linux64/THIRD_PARTY_NOTICES.chromedriver"
    }

So it seems to be as simple as the json file is updated wrongly?

**Comment by pjm002** [comment]
See https://github.com/SergeyPirogov/webdriver_manager and the comments there.  This is fixed but the package maintainer in involved in defending the Ukraine so I don't know when it will get migrated into the next release.

**Comment by password123456** [comment]
@pjm002 

i'm sorry for late response.
the chromedriver is manually downloaded, extracted, placed in the desired directory, and then executed. 

the find command in the guide is included as an example because some users might not know how to locate the downloaded ChromeDriver. 

The ChromeDriver is manually downloaded, extracted, placed in the desired directory, and then executed. The find command in the guide is included as an example because some users might not know how to locate the downloaded ChromeDriver. 

For downloading, installing, and running ChromeDriver, you might find it helpful to refer to [this guide](https://github.com/password123456/setup-selenium-with-chrome-driver-on-ubuntu_debian?tab=readme-ov-file#4-google-chrome-has-been-updated-where-can-i-download-chromedriver-and-how-do-i-install-it).

If I have misunderstood your instructions, 
please let me know :)
