### ISSUE TITLE
Any mirror storage for chromedriver?

### ISSUE THREAD

**Issue by hissain** [password123456/setup-selenium-with-chrome-driver-on-ubuntu_debian#6]
Some of users office workspace blocks googe storage. Is there any other alternative mirror storage for https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb file?

Thanks in advance

**Comment by password123456** [comment]
Sorry for the late response. I looked for other mirror sites, but it seems like only Google's domain exists. If Google's domain is blocked and direct download isn't possible, you might need to find a way to bypass the block or download the files from another source where someone has uploaded them. If you're part of a company, I believe the GitHub domain may not be blocked.

I checked GitHub, and found one repository: https://github.com/dreamshao/chromedriver. It appears to be maintained by an individual as a personal archive.

**Comment by hissain** [comment]
@password123456 thanks
